general.import = [
  "~/.config/alacritty/basic.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.bold]
#family = "Ac437 Acer VGA 8x8"
#family = "Fira Code SemiBold"
family = "ProggyClean CE Nerd Font"
#family = "Ubuntu Mono"
style = "Bold"

[font.bold_italic]
#family = "Ac437 Acer VGA 8x8"
#family = "Fira Code SemiBold"
family = "ProggyClean CE Nerd Font"
#family = "Ubuntu Mono"
style = "Bold"

[font.italic]
#family = "Ac437 Acer VGA 8x8"
#family = "Fira Code SemiBold"
family = "ProggyClean CE Nerd Font"
#family = "Ubuntu Mono"
style = "Regular Italic"

[font.normal]
#family = "Ac437 Acer VGA 8x8"
#family = "Fira Code SemiBold"
family = "ProggyClean CE Nerd Font"
#family = "Ubuntu Mono"
style = "Bold"
